require('dotenv').config({ path: require('path').join(__dirname, '../.env') });
const mongoose = require('mongoose');
const Accommodation = require('../models/Accommodation');

const accommodations = [
  // 서울특별시 강남구 (3개)
  {
    title: '강남 럭셔리 스위트',
    description: '강남 중심부의 고급 스위트룸, 도심 야경이 한눈에 보이는 최상층 숙소입니다.',
    address: { sido: '서울특별시', sigungu: '강남구', detail: '테헤란로 123' },
    capacity: { guests: 2, bedrooms: 1, beds: 1, bathrooms: 1 },
    price: 280000,
    accommodationType: '호텔',
    buildingType: '부티크호텔',
    images: { thumbnail: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800' },
    amenities: ['와이파이', '에어컨', '조식', '수영장', '피트니스', '발레파킹'],
    hostLanguages: ['한국어', '영어'],
    instantBook: true,
    rating: { overall: 4.9, cleanliness: 5.0, accuracy: 4.8, checkin: 4.9, communication: 4.9, location: 5.0, value: 4.7 },
    reviewCount: 156,
    isFeatured: true,
  },
  {
    title: '강남 모던 아파트',
    description: '강남구 역삼동 위치, 지하철 2호선 도보 3분 거리의 깔끔한 원룸형 아파트.',
    address: { sido: '서울특별시', sigungu: '강남구', detail: '역삼로 45' },
    capacity: { guests: 2, bedrooms: 1, beds: 1, bathrooms: 1 },
    price: 120000,
    accommodationType: '아파트',
    buildingType: '아파트',
    images: { thumbnail: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800' },
    amenities: ['와이파이', '에어컨', '주방', '세탁기', '넷플릭스'],
    hostLanguages: ['한국어'],
    instantBook: true,
    rating: { overall: 4.6, cleanliness: 4.7, accuracy: 4.6, checkin: 4.5, communication: 4.6, location: 4.8, value: 4.5 },
    reviewCount: 89,
    isFeatured: false,
  },
  {
    title: '청담동 럭셔리 빌라',
    description: '청담동 중심가에 위치한 프라이빗 빌라. 세련된 인테리어와 넓은 테라스가 자랑입니다.',
    address: { sido: '서울특별시', sigungu: '강남구', detail: '청담동 도산대로 200' },
    capacity: { guests: 4, bedrooms: 2, beds: 3, bathrooms: 2 },
    price: 290000,
    accommodationType: '빌라',
    buildingType: '부티크숙소',
    images: { thumbnail: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800' },
    amenities: ['와이파이', '에어컨', '주방', '바베큐', '테라스', '주차'],
    hostLanguages: ['한국어', '영어', '일본어'],
    instantBook: false,
    rating: { overall: 4.8, cleanliness: 4.9, accuracy: 4.8, checkin: 4.7, communication: 4.8, location: 4.9, value: 4.6 },
    reviewCount: 43,
    isFeatured: true,
  },
  // 서울특별시 종로구 (2개)
  {
    title: '경복궁 뷰 한옥스테이',
    description: '경복궁 바로 옆, 전통 한옥에서 즐기는 특별한 하룻밤. 마당과 전통 다도 체험 포함.',
    address: { sido: '서울특별시', sigungu: '종로구', detail: '삼청로 12' },
    capacity: { guests: 4, bedrooms: 2, beds: 2, bathrooms: 1 },
    price: 180000,
    accommodationType: '한옥',
    buildingType: '주택',
    images: { thumbnail: 'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=800' },
    amenities: ['와이파이', '에어컨', '주방', '세탁기', '한복 대여', '전통 다도'],
    hostLanguages: ['한국어', '영어'],
    instantBook: false,
    rating: { overall: 4.9, cleanliness: 4.8, accuracy: 4.9, checkin: 4.8, communication: 5.0, location: 5.0, value: 4.7 },
    reviewCount: 214,
    isFeatured: true,
  },
  {
    title: '인사동 감성 게스트하우스',
    description: '인사동 갤러리 골목 안에 자리한 아기자기한 게스트하우스. 예술적 감성이 물씬.',
    address: { sido: '서울특별시', sigungu: '종로구', detail: '인사동길 56' },
    capacity: { guests: 2, bedrooms: 1, beds: 1, bathrooms: 1 },
    price: 75000,
    accommodationType: '게스트하우스',
    buildingType: '주택',
    images: { thumbnail: 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800' },
    amenities: ['와이파이', '에어컨', '조식', '자전거 대여'],
    hostLanguages: ['한국어', '영어'],
    instantBook: true,
    rating: { overall: 4.5, cleanliness: 4.4, accuracy: 4.5, checkin: 4.6, communication: 4.7, location: 4.8, value: 4.6 },
    reviewCount: 98,
    isFeatured: false,
  },
  // 서울특별시 마포구 (1개)
  {
    title: '홍대 감성 아파트',
    description: '홍대 번화가 도보 5분, 모던한 인테리어의 아늑한 원룸. 젊고 활기찬 분위기 속 휴식.',
    address: { sido: '서울특별시', sigungu: '마포구', detail: '와우산로 30' },
    capacity: { guests: 2, bedrooms: 1, beds: 1, bathrooms: 1 },
    price: 95000,
    accommodationType: '원룸',
    buildingType: '아파트',
    images: { thumbnail: 'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800' },
    amenities: ['와이파이', '에어컨', '넷플릭스', '세탁기'],
    hostLanguages: ['한국어'],
    instantBook: true,
    rating: { overall: 4.5, cleanliness: 4.6, accuracy: 4.4, checkin: 4.5, communication: 4.5, location: 4.7, value: 4.4 },
    reviewCount: 112,
    isFeatured: false,
  },
  // 부산광역시 해운대구 (2개)
  {
    title: '해운대 오션뷰 펜션',
    description: '해운대 해수욕장 바로 앞, 바다가 한눈에 보이는 펜션. 가족 단위 여행객에 최적.',
    address: { sido: '부산광역시', sigungu: '해운대구', detail: '해운대해변로 100' },
    capacity: { guests: 6, bedrooms: 3, beds: 4, bathrooms: 2 },
    price: 220000,
    accommodationType: '펜션',
    buildingType: '별채',
    images: { thumbnail: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800' },
    amenities: ['와이파이', '에어컨', '바베큐', '주차', '세탁기', '해수욕장 용품'],
    hostLanguages: ['한국어', '영어'],
    instantBook: false,
    rating: { overall: 4.7, cleanliness: 4.8, accuracy: 4.7, checkin: 4.6, communication: 4.7, location: 5.0, value: 4.5 },
    reviewCount: 203,
    isFeatured: true,
  },
  {
    title: '마린시티 럭셔리 아파트',
    description: '해운대 마린시티 고층 아파트, 광안대교와 바다 전망이 환상적인 프리미엄 숙소.',
    address: { sido: '부산광역시', sigungu: '해운대구', detail: '마린시티1로 55' },
    capacity: { guests: 4, bedrooms: 2, beds: 2, bathrooms: 2 },
    price: 260000,
    accommodationType: '아파트',
    buildingType: '아파트',
    images: { thumbnail: 'https://images.unsplash.com/photo-1582268611958-ebfd161ef9cf?w=800' },
    amenities: ['와이파이', '에어컨', '주방', '수영장', '피트니스', '주차'],
    hostLanguages: ['한국어', '영어'],
    instantBook: true,
    rating: { overall: 4.8, cleanliness: 4.9, accuracy: 4.8, checkin: 4.7, communication: 4.8, location: 4.9, value: 4.6 },
    reviewCount: 77,
    isFeatured: true,
  },
  // 부산광역시 수영구 (1개)
  {
    title: '광안리 서퍼 하우스',
    description: '광안대교 야경이 아름다운 감각적인 단독주택. 서핑 보드 보관 가능.',
    address: { sido: '부산광역시', sigungu: '수영구', detail: '광안해변로 220' },
    capacity: { guests: 4, bedrooms: 2, beds: 3, bathrooms: 1 },
    price: 130000,
    accommodationType: '단독주택',
    buildingType: '주택',
    images: { thumbnail: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800' },
    amenities: ['와이파이', '에어컨', '주방', '자전거 대여', '서핑보드 보관'],
    hostLanguages: ['한국어', '영어'],
    instantBook: true,
    rating: { overall: 4.6, cleanliness: 4.5, accuracy: 4.6, checkin: 4.7, communication: 4.6, location: 4.8, value: 4.5 },
    reviewCount: 91,
    isFeatured: false,
  },
  // 제주특별자치도 제주시 (2개)
  {
    title: '제주 돌담 게스트하우스',
    description: '제주 전통 돌담으로 둘러싸인 아늑한 게스트하우스. 제주 시내 중심가 접근 용이.',
    address: { sido: '제주특별자치도', sigungu: '제주시', detail: '이도이동 탑동로 14' },
    capacity: { guests: 2, bedrooms: 1, beds: 1, bathrooms: 1 },
    price: 75000,
    accommodationType: '게스트하우스',
    buildingType: '주택',
    images: { thumbnail: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800' },
    amenities: ['와이파이', '조식', '자전거 대여', '공항 픽업'],
    hostLanguages: ['한국어'],
    instantBook: false,
    rating: { overall: 4.4, cleanliness: 4.3, accuracy: 4.4, checkin: 4.5, communication: 4.6, location: 4.3, value: 4.5 },
    reviewCount: 67,
    isFeatured: false,
  },
  {
    title: '제주 협재 오션뷰 독채',
    description: '협재 해수욕장 도보 2분, 에메랄드빛 바다가 보이는 프라이빗 독채 숙소.',
    address: { sido: '제주특별자치도', sigungu: '제주시', detail: '한림읍 협재리 해안로 56' },
    capacity: { guests: 6, bedrooms: 3, beds: 4, bathrooms: 2 },
    price: 240000,
    accommodationType: '독채',
    buildingType: '별채',
    images: { thumbnail: 'https://images.unsplash.com/photo-1499793983690-e29da59ef1c2?w=800' },
    amenities: ['와이파이', '에어컨', '주방', '바베큐', '주차', '해수욕 장비'],
    hostLanguages: ['한국어', '영어'],
    instantBook: false,
    rating: { overall: 4.8, cleanliness: 4.9, accuracy: 4.7, checkin: 4.8, communication: 4.8, location: 5.0, value: 4.6 },
    reviewCount: 134,
    isFeatured: true,
  },
  // 제주특별자치도 서귀포시 (2개)
  {
    title: '서귀포 풀빌라',
    description: '한라산과 바다가 보이는 프라이빗 풀빌라. 커플 및 가족 여행에 최적의 선택.',
    address: { sido: '제주특별자치도', sigungu: '서귀포시', detail: '중문관광로 300' },
    capacity: { guests: 6, bedrooms: 3, beds: 4, bathrooms: 2 },
    price: 290000,
    accommodationType: '펜션',
    buildingType: '별채',
    images: { thumbnail: 'https://images.unsplash.com/photo-1544551763-46a013bb70d5?w=800' },
    amenities: ['와이파이', '수영장', '바베큐', '주방', '주차', '넷플릭스'],
    hostLanguages: ['한국어', '영어'],
    instantBook: false,
    rating: { overall: 5.0, cleanliness: 5.0, accuracy: 5.0, checkin: 4.9, communication: 5.0, location: 5.0, value: 4.8 },
    reviewCount: 58,
    isFeatured: true,
  },
  {
    title: '정방폭포 근처 한옥 스테이',
    description: '동양 유일의 해안 폭포 정방폭포 인근, 고즈넉한 제주 한옥에서 즐기는 휴식.',
    address: { sido: '제주특별자치도', sigungu: '서귀포시', detail: '서귀동 정방로 8' },
    capacity: { guests: 4, bedrooms: 2, beds: 2, bathrooms: 1 },
    price: 160000,
    accommodationType: '한옥',
    buildingType: '주택',
    images: { thumbnail: 'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=800' },
    amenities: ['와이파이', '에어컨', '주방', '자전거 대여', '조식'],
    hostLanguages: ['한국어'],
    instantBook: true,
    rating: { overall: 4.7, cleanliness: 4.8, accuracy: 4.7, checkin: 4.6, communication: 4.8, location: 4.7, value: 4.6 },
    reviewCount: 82,
    isFeatured: false,
  },
  // 강원특별자치도 강릉시 (2개)
  {
    title: '강릉 바다 카페 스테이',
    description: '동해 바다를 바라보며 커피 향 가득한 감성 숙소. 강릉 커피거리 도보 5분.',
    address: { sido: '강원특별자치도', sigungu: '강릉시', detail: '강문동 해안로 77' },
    capacity: { guests: 2, bedrooms: 1, beds: 1, bathrooms: 1 },
    price: 110000,
    accommodationType: '독채',
    buildingType: '별채',
    images: { thumbnail: 'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?w=800' },
    amenities: ['와이파이', '에어컨', '조식 커피', '자전거 대여'],
    hostLanguages: ['한국어'],
    instantBook: true,
    rating: { overall: 4.7, cleanliness: 4.8, accuracy: 4.7, checkin: 4.6, communication: 4.7, location: 4.9, value: 4.6 },
    reviewCount: 145,
    isFeatured: false,
  },
  {
    title: '강릉 솔향기 펜션',
    description: '소나무 숲 사이 자리한 힐링 펜션. 가족 단위 여행객에게 추천하는 아늑한 공간.',
    address: { sido: '강원특별자치도', sigungu: '강릉시', detail: '성산면 어흘리 산촌로 33' },
    capacity: { guests: 6, bedrooms: 3, beds: 4, bathrooms: 2 },
    price: 160000,
    accommodationType: '펜션',
    buildingType: '별채',
    images: { thumbnail: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800' },
    amenities: ['와이파이', '바베큐', '주차', '세탁기', '산책로'],
    hostLanguages: ['한국어'],
    instantBook: false,
    rating: { overall: 4.5, cleanliness: 4.6, accuracy: 4.4, checkin: 4.5, communication: 4.5, location: 4.6, value: 4.4 },
    reviewCount: 78,
    isFeatured: false,
  },
  // 경상북도 경주시 (2개)
  {
    title: '경주 황리단길 한옥',
    description: '황리단길 중심에 위치한 신라 전통 한옥 숙소. 고풍스러운 분위기 속 현대적 편의시설.',
    address: { sido: '경상북도', sigungu: '경주시', detail: '황남동 포석로 130' },
    capacity: { guests: 4, bedrooms: 2, beds: 2, bathrooms: 1 },
    price: 140000,
    accommodationType: '한옥',
    buildingType: '주택',
    images: { thumbnail: 'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=800' },
    amenities: ['와이파이', '에어컨', '주방', '자전거 대여', '한복 대여'],
    hostLanguages: ['한국어', '영어'],
    instantBook: true,
    rating: { overall: 4.8, cleanliness: 4.9, accuracy: 4.8, checkin: 4.7, communication: 4.8, location: 4.9, value: 4.6 },
    reviewCount: 112,
    isFeatured: true,
  },
  {
    title: '불국사 뷰 민박',
    description: '불국사 인근, 신라 역사를 느낄 수 있는 아늑한 민박. 조용하고 깨끗한 가정집 분위기.',
    address: { sido: '경상북도', sigungu: '경주시', detail: '진현동 불국로 23' },
    capacity: { guests: 3, bedrooms: 1, beds: 2, bathrooms: 1 },
    price: 65000,
    accommodationType: '게스트하우스',
    buildingType: '주택',
    images: { thumbnail: 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800' },
    amenities: ['와이파이', '조식', '주차'],
    hostLanguages: ['한국어'],
    instantBook: false,
    rating: { overall: 4.3, cleanliness: 4.4, accuracy: 4.2, checkin: 4.3, communication: 4.5, location: 4.4, value: 4.5 },
    reviewCount: 54,
    isFeatured: false,
  },
  // 전북특별자치도 전주시 (2개)
  {
    title: '전주 한옥마을 스테이',
    description: '전주 한옥마을 한가운데 자리한 정통 한옥 체험 숙소. 한복 체험과 조식 비빔밥 포함.',
    address: { sido: '전북특별자치도', sigungu: '전주시', detail: '완산구 은행로 68' },
    capacity: { guests: 4, bedrooms: 2, beds: 2, bathrooms: 1 },
    price: 120000,
    accommodationType: '한옥',
    buildingType: '주택',
    images: { thumbnail: 'https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=800' },
    amenities: ['와이파이', '에어컨', '한복 체험', '조식', '자전거 대여'],
    hostLanguages: ['한국어', '영어'],
    instantBook: false,
    rating: { overall: 4.9, cleanliness: 4.9, accuracy: 4.9, checkin: 4.8, communication: 5.0, location: 5.0, value: 4.7 },
    reviewCount: 189,
    isFeatured: true,
  },
  {
    title: '전주 남부시장 근처 게스트하우스',
    description: '전주 남부시장과 객리단길 도보 3분. 야식과 전통시장 탐방에 최적인 위치.',
    address: { sido: '전북특별자치도', sigungu: '전주시', detail: '완산구 풍남동 시장로 17' },
    capacity: { guests: 2, bedrooms: 1, beds: 1, bathrooms: 1 },
    price: 55000,
    accommodationType: '게스트하우스',
    buildingType: '주택',
    images: { thumbnail: 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800' },
    amenities: ['와이파이', '에어컨', '조식', '세탁기'],
    hostLanguages: ['한국어'],
    instantBook: true,
    rating: { overall: 4.3, cleanliness: 4.2, accuracy: 4.3, checkin: 4.4, communication: 4.4, location: 4.5, value: 4.5 },
    reviewCount: 63,
    isFeatured: false,
  },
  // 인천광역시 중구 (1개)
  {
    title: '인천 차이나타운 게스트하우스',
    description: '인천 차이나타운 인근, 공항 접근성 최고의 숙소. 인천항과 개항장 문화거리 도보권.',
    address: { sido: '인천광역시', sigungu: '중구', detail: '차이나타운로 55' },
    capacity: { guests: 2, bedrooms: 1, beds: 1, bathrooms: 1 },
    price: 70000,
    accommodationType: '게스트하우스',
    buildingType: '기타',
    images: { thumbnail: 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800' },
    amenities: ['와이파이', '에어컨', '공항 셔틀', '조식'],
    hostLanguages: ['한국어', '영어', '중국어'],
    instantBook: true,
    rating: { overall: 4.2, cleanliness: 4.1, accuracy: 4.2, checkin: 4.3, communication: 4.3, location: 4.0, value: 4.4 },
    reviewCount: 96,
    isFeatured: false,
  },
  // 전라남도 여수시 (2개)
  {
    title: '여수 밤바다 펜션',
    description: '여수 밤바다가 눈앞에 펼쳐지는 로맨틱 오션뷰 펜션. 낚시 장비 무료 대여.',
    address: { sido: '전라남도', sigungu: '여수시', detail: '돌산읍 무술목길 80' },
    capacity: { guests: 4, bedrooms: 2, beds: 2, bathrooms: 1 },
    price: 190000,
    accommodationType: '펜션',
    buildingType: '별채',
    images: { thumbnail: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800' },
    amenities: ['와이파이', '에어컨', '바베큐', '낚시 장비', '주차'],
    hostLanguages: ['한국어'],
    instantBook: false,
    rating: { overall: 4.8, cleanliness: 4.7, accuracy: 4.8, checkin: 4.8, communication: 4.9, location: 4.9, value: 4.6 },
    reviewCount: 167,
    isFeatured: true,
  },
  {
    title: '여수 엑스포 해양공원 뷰 아파트',
    description: '여수세계박람회장 바로 앞, 아름다운 해양공원이 내려다보이는 깔끔한 아파트.',
    address: { sido: '전라남도', sigungu: '여수시', detail: '수정동 박람회길 22' },
    capacity: { guests: 4, bedrooms: 2, beds: 2, bathrooms: 1 },
    price: 130000,
    accommodationType: '아파트',
    buildingType: '아파트',
    images: { thumbnail: 'https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800' },
    amenities: ['와이파이', '에어컨', '주방', '세탁기', '주차'],
    hostLanguages: ['한국어'],
    instantBook: true,
    rating: { overall: 4.5, cleanliness: 4.6, accuracy: 4.4, checkin: 4.5, communication: 4.5, location: 4.7, value: 4.4 },
    reviewCount: 74,
    isFeatured: false,
  },
  // 강원특별자치도 속초시 (2개)
  {
    title: '속초 설악산 코타지',
    description: '설악산 등산로 입구 근처, 자연 속 통나무 코타지. 트레킹 후 온돌방에서 피로를 풀어보세요.',
    address: { sido: '강원특별자치도', sigungu: '속초시', detail: '설악동 설악로 190' },
    capacity: { guests: 5, bedrooms: 2, beds: 3, bathrooms: 1 },
    price: 145000,
    accommodationType: '독채',
    buildingType: '별채',
    images: { thumbnail: 'https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800' },
    amenities: ['와이파이', '난방', '주방', '바베큐', '주차'],
    hostLanguages: ['한국어'],
    instantBook: false,
    rating: { overall: 4.6, cleanliness: 4.7, accuracy: 4.6, checkin: 4.5, communication: 4.6, location: 4.8, value: 4.5 },
    reviewCount: 83,
    isFeatured: false,
  },
  {
    title: '속초 청초호 뷰 스튜디오',
    description: '청초호 호수 전망의 아늑한 스튜디오. 속초 시내와 아바이마을 도보권.',
    address: { sido: '강원특별자치도', sigungu: '속초시', detail: '중앙동 호반로 45' },
    capacity: { guests: 2, bedrooms: 1, beds: 1, bathrooms: 1 },
    price: 85000,
    accommodationType: '원룸',
    buildingType: '아파트',
    images: { thumbnail: 'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800' },
    amenities: ['와이파이', '에어컨', '주방', '세탁기'],
    hostLanguages: ['한국어'],
    instantBook: true,
    rating: { overall: 4.4, cleanliness: 4.5, accuracy: 4.3, checkin: 4.4, communication: 4.5, location: 4.5, value: 4.4 },
    reviewCount: 57,
    isFeatured: false,
  },
  // 대전광역시 유성구 (1개)
  {
    title: '대전 엑스포 모던 스튜디오',
    description: '엑스포 과학공원 인근 세련된 스튜디오. KAIST·충남대 접근성 좋아 출장·연구자에게 인기.',
    address: { sido: '대전광역시', sigungu: '유성구', detail: '엑스포로 123' },
    capacity: { guests: 2, bedrooms: 1, beds: 1, bathrooms: 1 },
    price: 80000,
    accommodationType: '원룸',
    buildingType: '아파트',
    images: { thumbnail: 'https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=800' },
    amenities: ['와이파이', '에어컨', '주방', '넷플릭스', '세탁기'],
    hostLanguages: ['한국어', '영어'],
    instantBook: true,
    rating: { overall: 4.4, cleanliness: 4.5, accuracy: 4.3, checkin: 4.4, communication: 4.4, location: 4.3, value: 4.5 },
    reviewCount: 61,
    isFeatured: false,
  },
  // 경상남도 통영시 (2개)
  {
    title: '통영 케이블카 뷰 펜션',
    description: '미륵산 케이블카 근처, 한려수도 절경이 보이는 펜션. 통영 루지와 케이블카 도보 접근.',
    address: { sido: '경상남도', sigungu: '통영시', detail: '미수동 미륵산로 300' },
    capacity: { guests: 4, bedrooms: 2, beds: 2, bathrooms: 1 },
    price: 155000,
    accommodationType: '펜션',
    buildingType: '별채',
    images: { thumbnail: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=800' },
    amenities: ['와이파이', '에어컨', '바베큐', '낚시 장비', '주차'],
    hostLanguages: ['한국어'],
    instantBook: false,
    rating: { overall: 4.7, cleanliness: 4.8, accuracy: 4.7, checkin: 4.6, communication: 4.7, location: 4.8, value: 4.5 },
    reviewCount: 102,
    isFeatured: false,
  },
  {
    title: '통영 동피랑 마을 게스트하우스',
    description: '알록달록 벽화마을 동피랑 언덕 위, 통영항이 내려다보이는 아기자기한 게스트하우스.',
    address: { sido: '경상남도', sigungu: '통영시', detail: '동피랑길 25' },
    capacity: { guests: 3, bedrooms: 1, beds: 2, bathrooms: 1 },
    price: 70000,
    accommodationType: '게스트하우스',
    buildingType: '주택',
    images: { thumbnail: 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800' },
    amenities: ['와이파이', '에어컨', '조식', '자전거 대여'],
    hostLanguages: ['한국어'],
    instantBook: true,
    rating: { overall: 4.5, cleanliness: 4.4, accuracy: 4.5, checkin: 4.6, communication: 4.6, location: 4.7, value: 4.6 },
    reviewCount: 88,
    isFeatured: false,
  },
  // 경기도 수원시 (1개)
  {
    title: '수원 화성 뷰 게스트하우스',
    description: '유네스코 세계문화유산 수원화성 바로 옆 아늑한 게스트하우스. 성곽 야경이 아름다운 곳.',
    address: { sido: '경기도', sigungu: '수원시', detail: '팔달구 화서문로 44' },
    capacity: { guests: 2, bedrooms: 1, beds: 1, bathrooms: 1 },
    price: 75000,
    accommodationType: '게스트하우스',
    buildingType: '주택',
    images: { thumbnail: 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?w=800' },
    amenities: ['와이파이', '에어컨', '자전거 대여', '주차'],
    hostLanguages: ['한국어', '영어'],
    instantBook: true,
    rating: { overall: 4.4, cleanliness: 4.3, accuracy: 4.4, checkin: 4.5, communication: 4.5, location: 4.6, value: 4.5 },
    reviewCount: 58,
    isFeatured: false,
  },
];

const seed = async () => {
  try {
    await mongoose.connect(process.env.MONGODB_URI);
    console.log('Connected to MongoDB');

    await Accommodation.deleteMany({});
    console.log('Cleared existing accommodations');

    await Accommodation.insertMany(accommodations);
    console.log(`Seeded ${accommodations.length} accommodations`);

    await mongoose.disconnect();
    console.log('Done');
  } catch (error) {
    console.error('Seed error:', error.message);
    process.exit(1);
  }
};

seed();
